### ISSUE TITLE
[Bug] App crashes when offering a trip

### ISSUE THREAD

**Issue by VanessaLange** [AMOS-2015/amos-ss15-proj2#6]
Sometimes, but repeatedly, the currentLocation when offering a trip is null which causes the app to crash when trying to extract the Latitude: 
`b.putDouble("fromLat", currentLocation.getLatitude());`

    Full StackTrace:
    3032-3032/org.croudtrip E/AndroidRuntime﹕ FATAL EXCEPTION: main
        Process: org.croudtrip, PID: 3032
        java.lang.NullPointerException: Attempt to invoke virtual method 'double android.location.Location.getLatitude()' on a null object reference
            at org.croudtrip.fragments.OfferTripFragment$8.onClick(OfferTripFragment.java:379)
            at android.view.View.performClick(View.java:4756)
            at android.view.View$PerformClick.run(View.java:19748)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:898)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:693)

**Comment by Webbed90** [comment]
Added to Product Backlog as "B27 - [BUG] Application crash when offering a trip"
